name: Publish NuGet Package

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'ga'
      - name: Restore dependencies
        run: dotnet restore
      - name: Set version
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" =~ refs/tags/v(.*) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            VERSION=$(date +'%Y.%m.%d.%H%M')
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
                PR_NUM=${{ github.event.pull_request.number }}
                VERSION="$VERSION-pr$PR_NUM"
              else
                echo "Not a merged PR, skipping publish."
                exit 1
              fi
            elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              VERSION="$VERSION-manual"
            fi
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Pack Common NuGet package
        run: |
          dotnet pack ViewLocator.Common/ViewLocator.Common.csproj \
            --configuration Release \
            --no-restore \
            -p:PackageVersion=${{ steps.set_version.outputs.version }} \
            -o ./nupkg
      - name: Pack Generator NuGet package
        run: |
          dotnet pack ViewLocator.Generator/ViewLocator.Generator.csproj \
            --configuration Release \
            --no-restore \
            -p:PackageVersion=${{ steps.set_version.outputs.version }} \
            -o ./nupkg
      - name: Publish to NuGet.org
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key ${{ secrets.NUGET_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --source "github" \
            --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg
